name = "tituscrm"
account_id = "b52d78b0731686babcdbfb81cb71d77f"
compatibility_date = "2024-09-23"
workers_dev = true
main = "worker.js"

routes = [
  { pattern = "www.titus-crm.com", custom_domain = true },
  { pattern = "demo.titus-crm.com", custom_domain = true }
]

[assets]
directory = "./"
binding = "ASSETS"
